name: release_test

on:
  workflow_dispatch:
    inputs:
      Version:
        description: 'Example: v1.2.3'
        required: true

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Generate_release_changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.Version }}
          release_name: Release ${{ github.event.inputs.Version }}
          body: |
            ${{ steps.Generate_release_changelog.outputs.changelog }}
          draft: false
          prerelease: false
